# Generated by Django 5.2.5 on 2025-09-04 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('kilometraje', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('emergencia', 'Emergencia')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('kilometraje_actual', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taller', models.CharField(max_length=100)),
                ('completado', models.BooleanField(default=False)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.vehiculo')),
            ],
        ),
    ]
